USE [master]
GO

CREATE DATABASE [CadastroAgendaSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CadastroAgendaSQL', FILENAME = N'E:\MeusProjetos\CSharp-2010\Capitulo 10\AgendaDB\CadastroAgendaSQL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CadastroAgendaSQL_log', FILENAME = N'E:\MeusProjetos\CSharp-2010\Capitulo 10\AgendaDB\CadastroAgendaSQL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CadastroAgendaSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CadastroAgendaSQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CadastroAgendaSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CadastroAgendaSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CadastroAgendaSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CadastroAgendaSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CadastroAgendaSQL] SET  MULTI_USER 
GO

ALTER DATABASE [CadastroAgendaSQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CadastroAgendaSQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CadastroAgendaSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CadastroAgendaSQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CadastroAgendaSQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CadastroAgendaSQL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CadastroAgendaSQL] SET  READ_WRITE 
GO
